# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

hello:
  path: /hello
  controller: App\Controller\HelloController::index
  methods: [GET]

loved_game_create:
    path: /loved-games
    controller: App\Controller\LovedGameController::create
    methods: [POST]

loved_game_delete:
    path: /loved-games/{id}
    controller: App\Controller\LovedGameController::delete
    methods: [DELETE]
    requirements:
        id: '\d+'

player_loved_games:
    path: /players/{id}/loved-games
    controller: App\Controller\PlayerController::getLovedGames
    methods: [GET]
    requirements:
        'id': '\d+'

games_most_loved:
    path: /games/most-loved/
    controller: App\Controller\GameController::getMostLoved
    methods: [GET]

games_read_all:
    path: /games
    controller: App\Controller\GameController::getAll
    methods: [GET]
